# Create a namespace named "web"
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
# Create a role named "web-admins-role" with
# full access to objects in the "web" namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: web-admins-role
 namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
# Create a role binding named "web-admins-binding"
# to attach the "web-admins-role" role to the "web-admins" group
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-admins-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-admins-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: web-admins-group
